<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'proname' => 'iPhone 15 Pro Max',
                'price' => 34990000,
                'description' => 'Flagship Apple năm 2023',
                'fileName' => 'iphone15.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Samsung Galaxy S24 Ultra',
                'price' => 29990000,
                'description' => 'Camera đỉnh, hiệu năng vượt trội',
                'fileName' => 's24ultra.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Xiaomi 14',
                'price' => 19990000,
                'description' => 'Snapdragon 8 Gen 3, sạc siêu nhanh',
                'fileName' => 'xiaomi14.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'OPPO Reno 11F',
                'price' => 8990000,
                'description' => 'Chụp ảnh chân dung đẹp',
                'fileName' => 'reno11f.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'MacBook Air M2',
                'price' => 27990000,
                'description' => 'Laptop siêu mỏng nhẹ, pin trâu',
                'fileName' => 'mba_m2.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'ASUS ROG Strix G16',
                'price' => 32990000,
                'description' => 'Laptop gaming cực mạnh',
                'fileName' => 'rog_strix.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Dell XPS 13',
                'price' => 24990000,
                'description' => 'Ultrabook sang trọng, gọn nhẹ',
                'fileName' => 'xps13.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'iPad Pro M2 11-inch',
                'price' => 26990000,
                'description' => 'Tablet mạnh mẽ nhất 2023',
                'fileName' => 'ipadpro_m2.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Samsung Galaxy Tab S9',
                'price' => 22990000,
                'description' => 'Màn AMOLED 120Hz, S-Pen đi kèm',
                'fileName' => 'tabs9.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Lenovo Legion 5 Pro',
                'price' => 28990000,
                'description' => 'Laptop chơi game tản nhiệt tốt',
                'fileName' => 'legion5.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Realme GT Neo 6',
                'price' => 13990000,
                'description' => 'Hiệu năng mạnh, giá hợp lý',
                'fileName' => 'realme_gt_neo6.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'HP Spectre x360',
                'price' => 30990000,
                'description' => 'Laptop cao cấp xoay gập 2 trong 1',
                'fileName' => 'hp_spectre.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'iPad Air M1',
                'price' => 18990000,
                'description' => 'Hiệu năng M1, giá dễ tiếp cận',
                'fileName' => 'ipadair_m1.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Asus Zenbook 14 OLED',
                'price' => 21990000,
                'description' => 'Màn hình OLED tuyệt đẹp, siêu nhẹ',
                'fileName' => 'zenbook14.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Samsung Galaxy Z Fold5',
                'price' => 40990000,
                'description' => 'Điện thoại gập cao cấp nhất của Samsung',
                'fileName' => 'zfold5.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Nokia G21 6',
                'price' => 10782335,
                'description' => 'Smartphone hiệu năng ổn định, giá tốt.',
                'fileName' => 'nokia_g21.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Acer Swift 5 7',
                'price' => 30001494,
                'description' => 'Laptop hiệu suất cao, thích hợp cho học tập và làm việc.',
                'fileName' => 'acer_swift_5.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Xiaomi Pad 6 9',
                'price' => 14877495,
                'description' => 'Tablet giải trí và làm việc tiện lợi.',
                'fileName' => 'xiaomi_pad_6.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 16',
                'price' => 16990000,
                'description' => 'Mô tả sản phẩm 16',
                'fileName' => 'product16.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 17',
                'price' => 17990000,
                'description' => 'Mô tả sản phẩm 17',
                'fileName' => 'product17.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 18',
                'price' => 18990000,
                'description' => 'Mô tả sản phẩm 18',
                'fileName' => 'product18.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 19',
                'price' => 19990000,
                'description' => 'Mô tả sản phẩm 19',
                'fileName' => 'product19.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 20',
                'price' => 20990000,
                'description' => 'Mô tả sản phẩm 20',
                'fileName' => 'product20.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 21',
                'price' => 21990000,
                'description' => 'Mô tả sản phẩm 21',
                'fileName' => 'product21.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 22',
                'price' => 22990000,
                'description' => 'Mô tả sản phẩm 22',
                'fileName' => 'product22.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 23',
                'price' => 23990000,
                'description' => 'Mô tả sản phẩm 23',
                'fileName' => 'product23.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 24',
                'price' => 24990000,
                'description' => 'Mô tả sản phẩm 24',
                'fileName' => 'product24.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 25',
                'price' => 25990000,
                'description' => 'Mô tả sản phẩm 25',
                'fileName' => 'product25.jpg',
                'status' => 1,
                'cateid' => 1,
                'brandid' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 26',
                'price' => 26990000,
                'description' => 'Mô tả sản phẩm 26',
                'fileName' => 'product26.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 27',
                'price' => 27990000,
                'description' => 'Mô tả sản phẩm 27',
                'fileName' => 'product27.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 28',
                'price' => 28990000,
                'description' => 'Mô tả sản phẩm 28',
                'fileName' => 'product28.jpg',
                'status' => 1,
                'cateid' => 2,
                'brandid' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 29',
                'price' => 29990000,
                'description' => 'Mô tả sản phẩm 29',
                'fileName' => 'product29.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'proname' => 'Product 30',
                'price' => 30990000,
                'description' => 'Mô tả sản phẩm 30',
                'fileName' => 'product30.jpg',
                'status' => 1,
                'cateid' => 3,
                'brandid' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
